# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Project page: https://readthedocs.org/projects/pep-previews/

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"

  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - make dirhtml JOBS=$(nproc) BUILDDIR=_readthedocs/html

sphinx:
  builder: dirhtml
  configuration: peps/conf.py

search:
  ignore: ['*']
