
   graph TD;
     A[Stack frame]-- f1 -->B[Fraction instance 1]
     B-- n -->1
     B-- d -->3
     A-- f2 -->D[Fraction instance 2]
     D-- n -->2
     D-- d -->7
     B-- \_\_class__ -->E[Fraction]
     D-- \_\_class__ -->E
     1-- \_\_class__ -->int
     3-- \_\_class__ -->int
     2-- \_\_class__ -->int
     7-- \_\_class__ -->int
     int -- \_\_class__ -->type
     E-- \_\_init__ -->AA[Function 3]
     E-- \_\_add__ -->BB[Function 4]
     E-- \_\_repr__ -->CC[Function 5]
     E-- \_\_class__ -->type
     A-- gcd -->DD[Function 1]
     A-- print_fraction -->EE[Function 2]
     AA-- gcd -->DD
     BB-- Fraction -->E
     int -- superclass -->O[object]:::imm
     E -- superclass -->O
     O -- \_\_class__ -->type

     B:::imm
     1:::imm
     3:::imm
     2:::imm
     7:::imm
     int:::imm
     type:::imm
     E:::imm
     AA:::imm
     BB:::imm
     CC:::imm
     DD:::imm
     classDef imm fill:#ADD8E6,stroke:#003366,stroke-width:1px,color:#003366;
     linkStyle 1,2,6,8,9,10,11,12,13,14,15,16,19,20,21,22,23 stroke:#00f,stroke-width:1px,color:blue;
