
   graph LR
    subgraph Sub 1
      A[A]
      D[D]
    end

    subgraph Sub 2
      B[B]
    end

    C:::imm

    A ----> C
    B ----> C
    C ----> D
    A -. GIL 1 .-> C
    B -. GIL 2 .-> C
    C -. GIL 1 .-> D
    C -. GIL 2 .-> D

    classDef imm fill:#ADD8E6,stroke:#003366,stroke-width:1px,color:#003366;
    linkStyle 4,6 stroke:#f00,stroke-width:1px,color:blue;
    linkStyle 3,5 stroke:#90f,stroke-width:1px,color:blue;
