
   graph TD;
     A[Stack frame]-- d -->B[DieInstance]:::imm
     B-- sides -->12:::imm
     B-- \_\_class__ -->C[Die]:::imm
     C-- \_\_class__ -->D[type]:::imm
     C-- \_\_bases__-->T[tuple]:::imm
     T--> E[object]:::imm
     E-- \_\_class__ -->F[type]:::imm
     C-- \_\_init__ -->G[Function object]:::imm
     C-- set_sides -->H[Function object]:::imm
     C-- roll -->I[Function object]:::imm
     classDef imm fill:#ADD8E6,stroke:#003366,stroke-width:1px,color:#003366;
     linkStyle 1,2,3,4,5,6,7,8,9 stroke:#00f,stroke-width:1px,color:blue;
