flowchart TD
    A["Stack frame"] -- f1 --> B["Fraction instance 1"]
    A -- f2 --> D["Fraction instance 2"]
    B -- \_\_class__ --> E["Fraction"]
    B -- n --> 1["1"]
    B -- d --> 3["3"]
    D -- n --> 2["2"]
    D -- d --> 7["7"]
    D -- \_\_class__ --> E
    1 -- \_\_class__ --> int["int"]
    3 -- \_\_class__ --> int
    2 -- \_\_class__ --> int
    7 -- \_\_class__ --> int
    int -- \_\_class__ --> type["type"]
    E -- \_\_init__ --> AA["Function 3"]
    E -- \_\_add__ --> BB["Function 4"]
    E -- \_\_repr__ --> CC["Function 5"]
    E -- \_\_class__ --> type
    A -- utils --> DD["utils module"]
    AA -- gcd --> DD
    BB -- Fraction --> E
    int -- superclass --> O["object"]
    E -- superclass --> O
    O -- \_\_class__ --> type
    DD -- gcd --> XX["Function 1"]

     B:::imm
     1:::imm
     3:::imm
     2:::imm
     7:::imm
     E:::imm
     int:::imm
     type:::imm
     AA:::imm
     BB:::imm
     CC:::imm
     DD:::imm
     O:::imm
     XX:::imm
    classDef imm fill:#ADD8E6,stroke:#003366,stroke-width:1px,stroke-dasharray: 4 2,color:#003366
    linkStyle 4 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 5 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 6 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 8 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 9 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 10 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 11 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 12 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 13 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 14 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 15 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 16 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 18 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 19 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 20 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 21 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 22 stroke:#00f,stroke-width:2px,color:blue,fill:none
    linkStyle 23 stroke:#00f,stroke-width:2px,color:blue,fill:none
