
   graph
     subgraph Module1
       A[Type1]
       B[Func1]
       X[Var1]
       subgraph Module2
           C[Type2]
           D[Func2]
           Y[Var2]
       end
     end

     subgraph Module3
       E[Type3]
       EE[Type4]
       Z[Var3]
       F[Func3]
     end

     subgraph Program
       O1
       O2
       x
       y
       m3
       m1
     end

     A -- calls --> B
     B -- uses --> C
     B -- imports --> Module2
     B -- reads --> X
     B -- writes --> X
     C -- calls --> D
     C -- writes --> Y

     E -- reads --> Z
     F -- writes --> Z
     
     F -- imports --> Module2

     EE -- extends --> E
     
     O1 -- \_\_class__ --> EE
     O2 -- \_\_class__ --> A
     x --> O1
     y --> O2
     m1 -- imports --> Module1
     m3 -- imports --> Module3
