
   graph LR
     subgraph Sub 1
       A[A]
     end

     subgraph Sub 2
       B[B]
     end

     C:::imm
     D:::imm

     A ----> C
     B ----> C
     C -- \_\_class__ --> D

    classDef imm fill:#ADD8E6,stroke:#003366,stroke-width:1px,stroke-dasharray: 4 2,color:#003366;
    linkStyle 2 stroke:#00f,stroke-width:2px,color:blue;
