
   graph LR
     subgraph Sub 1
       A[A]
       D1[interpreter-local storage]
       E[E]
     end

     subgraph Sub 2
       B[B]
       D2[interpreter-local storage]
       F[F]
     end

     C[Prime factoriser]:::imm

     A ----> C
     B ----> C
     C ----> D1
     C ----> D2
     D1 ----> E
     D2 ----> F
     A -. GIL 1 .-> C
     C -. GIL 1 .-> D1
     D1 -. GIL 1 .-> E
     B -. GIL 2 .-> C
     C -. GIL 2 .-> D2
     D2 -. GIL 2 .-> F

     classDef imm fill:#ADD8E6,stroke:#003366,stroke-width:1px,color:#003366;
     classDef fake_imm fill:#aaa,stroke:#000,stroke-width:1px;
     linkStyle 6,7,8 stroke:#f00,stroke-width:1px,color:blue;
     linkStyle 9,10,11 stroke:#90f,stroke-width:1px,color:blue;
