
   graph LR
     subgraph Sub 1
       A[A]
     end

     subgraph Sub 2
       B[B]
     end

     C[Cell]:::imm
     D[Shared field]:::fake_imm
     E[2]:::imm

     A ----> C
     B ----> C
     C ----> D
     D ----> E
     A -. GIL 1 .-> C
     C -. GIL 1 .-> D
     D -. GIL 1 .-> E
     B -. GIL 2 .-> C
     C -. GIL 2 .-> D
     D -. GIL 2 .-> E

     classDef imm fill:#ADD8E6,stroke:#003366,stroke-width:1px,color:#003366;
     classDef fake_imm fill:#aaa,stroke:#000,stroke-width:1px;
     linkStyle 4,5,6 stroke:#f00,stroke-width:1px,color:blue;
     linkStyle 7,8,9 stroke:#90f,stroke-width:1px,color:blue;
