   graph TD;
     A[Stack frame]-- f1 -->B[FractionInstance1]
     B-- n -->1:::imm
     B-- d -->3:::imm
     A-- f2 -->D[FractionInstance2]
     D-- n -->2:::imm
     D-- d -->7:::imm
     classDef imm fill:#ADD8E6,stroke:#003366,stroke-width:1px,stroke-dasharray: 4 2,color:#003366;
