
   graph TD;
     A[Stack frame]-- f1 -->B[Fraction instance 1]
     B-- n -->1:::imm
     B-- d -->3:::imm
     A-- f2 -->D[Fraction instance 2]
     D-- n -->2:::imm
     D-- d -->7:::imm
     B-- \_\_class__ -->E[Fraction]
     D-- \_\_class__ -->E
     1-- \_\_class__ -->int:::imm
     3-- \_\_class__ -->int
     2-- \_\_class__ -->int
     7-- \_\_class__ -->int
     int -- \_\_class__ -->type:::imm
     E-- \_\_init__ -->AA[Function 3]
     E-- \_\_add__ -->BB[Function 4]
     E-- \_\_repr__ -->CC[Function 5]
     E-- \_\_class__ -->type:::imm
     A-- gcd -->DD[Function 1]
     A-- print_fraction -->EE[Function 2]
     AA-- gcd -->DD
     BB-- Fraction -->E
     int -- superclass -->O[object]:::imm
     E -- superclass -->O
     O -- \_\_class__ -->type:::imm
     classDef imm fill:#ADD8E6,stroke:#003366,stroke-width:1px,color:#003366;
     linkStyle 8,9,10,11,12,21,23 stroke:#00f,stroke-width:1px,color:blue;
