name: Test Sphinx Extensions

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "pep_sphinx_extensions/**"
      - "tox.ini"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "pep_sphinx_extensions/**"
      - "tox.ini"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"
        - "3.15"
        os:
        - "windows-latest"
        - "macos-latest"
        - "ubuntu-latest"

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install uv
        uses: hynek/setup-cached-uv@4300ec2180bc77d705e626a34e381b81a4772c51 # v2.5.0
        with:
          cache-dependency-path: |
            requirements.txt

      - name: Run tests with tox
        run: |
          uvx --with tox-uv tox -e py -- -v --cov-report term

      - name: Upload coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          flags: ${{ matrix.os }}
          name: ${{ matrix.os }} Python ${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
